services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
      - DB_HOST=db
      - DB_PORT=5432
      # used by bootstrap when creating a site
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - REDIS_CACHE=redis://redis:6379
      - REDIS_QUEUE=redis://redis:6379
      - REDIS_SOCKETIO=redis://redis:6379
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - frappe-tutorial-network

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - frappe-tutorial-network
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    networks:
      - frappe-tutorial-network
    ports:
      - "6379:6379"

networks:
  frappe-tutorial-network:
    driver: bridge

volumes:
  postgres-data:
    name: postgres-frappe-tutorial
